// <auto-generated />
using System;
using ClassCloud.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassCloud.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ClassCloudDbContext))]
    partial class ClassCloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Courses_CreatedAtUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Courses_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Courses_Id");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Courses_CourseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseRegistrationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int>("CourseStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseRegistrations_RegistrationDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseRegistrations_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_CourseRegistrations_Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("CourseStatusId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("CourseRegistrations");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseSessions_CreatedAtUtc");

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseSessions_EndDate");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseSessions_StartDate");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseSessions_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_CourseSessions_Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LocationId");

                    b.ToTable("CourseSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseSession_MaxParticipants", "[MaxParticipants] > 0");
                        });
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CourseStatus_Id");

                    b.ToTable("CourseStatus");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Locations_CreatedAtUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Locations_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Locations_Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.ParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Participants_CreatedAtUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Participants_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Participants_Id");

                    b.HasIndex(new[] { "Email" }, "UQ_Participants_Email")
                        .IsUnique();

                    b.ToTable("Participants", t =>
                        {
                            t.HasCheckConstraint("UQ_Participants_Email_NotEmpty", "LTRIM(RTRIM([Email])) <> ''");
                        });
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.TeacherCourseSessionEntity", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TeacherId", "CourseSessionId")
                        .HasName("PK_TeacherCourseSessions_Id");

                    b.HasIndex("CourseSessionId");

                    b.ToTable("TeacherCourseSessions");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.TeacherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Teachers_CreatedAtUtc");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Teachers_UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Teachers_Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseRegistrationEntity", b =>
                {
                    b.HasOne("ClassCloud.Domain.Entities.CourseSessionEntity", "CourseSession")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassCloud.Domain.Entities.CourseStatusEntity", "CourseStatus")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("CourseStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassCloud.Domain.Entities.ParticipantEntity", "Participant")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("CourseStatus");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseSessionEntity", b =>
                {
                    b.HasOne("ClassCloud.Domain.Entities.CourseEntity", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassCloud.Domain.Entities.LocationEntity", "Location")
                        .WithMany("CourseSessions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.TeacherCourseSessionEntity", b =>
                {
                    b.HasOne("ClassCloud.Domain.Entities.CourseSessionEntity", "CourseSession")
                        .WithMany("TeacherCourseSessions")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassCloud.Domain.Entities.TeacherEntity", "Teacher")
                        .WithMany("TeacherCourseSessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseEntity", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseSessionEntity", b =>
                {
                    b.Navigation("CourseRegistrations");

                    b.Navigation("TeacherCourseSessions");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.CourseStatusEntity", b =>
                {
                    b.Navigation("CourseRegistrations");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.LocationEntity", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.ParticipantEntity", b =>
                {
                    b.Navigation("CourseRegistrations");
                });

            modelBuilder.Entity("ClassCloud.Domain.Entities.TeacherEntity", b =>
                {
                    b.Navigation("TeacherCourseSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
